### ISSUE TITLE
Get project working

### ISSUE THREAD

**Issue by emtek995** [40PlusBaddies/birthdayApp#13]
Doesn't currently run.

**Comment by marianaWest** [comment]
also tried and didn't work. I get this message: 
const MongoStore = require("connect-mongo")(session);
                                         ^
TypeError: Class constructor MongoStore cannot be invoked without 'new'

I found some possible solutions on StackOverflow but they didn't solve the problem (downgrading connect-mongo to ^3). Is that the problem you're having?
